---
format_version: 1.3.0
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
trigger_map:
- push_branch: "*"
  workflow: primary
- pull_request_source_branch: "*"
  workflow: primary
workflows:
  primary:
    steps:
    - activate-ssh-key@4.0.3:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@4.0.12: {}
    - install-missing-android-tools@2.2.0: {}
    - script@1.1.5:
        inputs:Switched to shell script from Gradle runner at bitrise (#36)
        - content: |-
            #!/usr/bin/env bash
            # fail if any commands fails
            set -e
            # debug log
            set -x

            unset ANDROID_NDK_HOME

            ./gradlew assembleDebug testDebug jacocoTestReport lintDebug buildDashboard assembleDebugAndroidTest crashlyticsUploadDistributionDebug -PversionCode=$BITRISE_BUILD_NUMBER -PfabricApiKey=$FABRIC_API_KEY -PfabricApiSecret=$FABRIC_API_SECRET
        title: Gradle Build/Test/Analyse/Distribute
# disabled because of https://github.com/vgaidarji/ci-matters/issues/35
#    - gradle-runner@1.8.3:
#        title: Gradle Build/Test/Analyse/Distribute
#        inputs:
#        - gradle_task: assembleDebug testDebug jacocoTestReport
#            lintDebug buildDashboard crashlyticsUploadDistributionDebug -PversionCode=$BITRISE_BUILD_NUMBER
#            -PfabricApiKey=$FABRIC_API_KEY -PfabricApiSecret=$FABRIC_API_SECRET
#        - mapping_file_exclude_filter: ''
    - gradle-coveralls@1.0.1:
        inputs:
        - coveralls_task: coveralls -PversionCode=$BITRISE_BUILD_NUMBER -PfabricApiKey=$FABRIC_API_KEY
            -PfabricApiSecret=$FABRIC_API_SECRET
        - coveralls_repo_token: "$COVERALLS_REPO_TOKEN"
    - deploy-to-bitrise-io@1.3.18:
        title: Deploy test reports to Bitrise.io
        inputs:
        - deploy_path: "$BITRISE_SOURCE_DIR/app/build/reports/jacocoTestReport/"
        - notify_email_list: ''
    - deploy-to-bitrise-io@1.3.18:
        title: Deploy APK to Bitrise.io
app:
  envs:
  - opts:
      is_expand: false
    GRADLE_BUILD_FILE_PATH: build.gradle
  - opts:
      is_expand: false
    GRADLE_TASK: assembleDebug
  - opts:
      is_expand: false
    GRADLEW_PATH: "./gradlew"
