name: Build, Test and Distribute
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      uses: vgaidarji/android-github-actions-build@v1.0.1
      env:
        FABRIC_API_KEY: ${{ secrets.FABRIC_API_KEY }}
        FABRIC_API_SECRET: ${{ secrets.FABRIC_API_SECRET }}
      with:
        args: "sdkmanager 'platforms;android-26' && ./gradlew assembleDebug"
    - name: Check
      uses: vgaidarji/android-github-actions-build@v1.0.1
      env:
        FABRIC_API_KEY: ${{ secrets.FABRIC_API_KEY }}
        FABRIC_API_SECRET: ${{ secrets.FABRIC_API_SECRET }}
      with:
        args: "./gradlew testDebug jacocoTestReport lintDebug buildDashboard"
    - name: Distribute
      uses: vgaidarji/android-github-actions-build@v1.0.1
      env:
        FABRIC_API_KEY: ${{ secrets.FABRIC_API_KEY }}
        FABRIC_API_SECRET: ${{ secrets.FABRIC_API_SECRET }}
      with:
        args: "./gradlew crashlyticsUploadDistributionDebug"
    - name: Publish Code Coverage
      uses: vgaidarji/android-github-actions-build@v1.0.1
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      with:
        args: "./gradlew coveralls"
  androidTest:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        env:
          FABRIC_API_KEY: ${{ secrets.FABRIC_API_KEY }}
          FABRIC_API_SECRET: ${{ secrets.FABRIC_API_SECRET }}
        with:
          api-level: 29
          arch: x86
          disable-animations: true
          script: ./gradlew connectedAndroidTest --stacktrace
